spring:
  application:
   name: config-server	

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
  service-url:
  defaultzone: http://localhost:8761/eureka        


